version: "3.7"
services:

    db:
      image: postgres:latest
      restart: always
      ports:
        - "5432:5432"
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
        POSTGRES_PASSWORD: centralesupelec
        POSTGRES_USER: admin
        
